# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SuggestCatForRandomCoffeeRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SuggestCatForRandomCoffeeRequest - a model defined in OpenAPI

        cat_id: The cat_id of this SuggestCatForRandomCoffeeRequest.
        name: The name of this SuggestCatForRandomCoffeeRequest.
        breed: The breed of this SuggestCatForRandomCoffeeRequest.
    """

    cat_id: int = Field(alias="catId")
    name: str = Field(alias="name")
    breed: str = Field(alias="breed")

SuggestCatForRandomCoffeeRequest.update_forward_refs()
