# coding: utf-8

"""
    cat-random-coffee-recommender API

    Service for recommending cat pairs for random coffee.

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from cat_recommender.apis.random_coffee_api import router as RandomCoffeeApiRouter

app = FastAPI(
    title="cat-random-coffee-recommender API",
    description="Service for recommending cat pairs for random coffee. ",
    version="0.0.1",
)

app.include_router(RandomCoffeeApiRouter)
