@startuml
'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!include <c4/C4_Container.puml>

'ref http://plantuml.com/stdlib
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>

Person(user, User)

System_Boundary(c1, "test-assignment") {
    ContainerDb(database, "Database", "SQL Database")
    Container(backend_api, "cat-api", "Java/Kotlin, Docker Container", "Provides some functionality via API.")
    Container(python_api, "cat-recommender-api", "Python, FastAPI, Docker Container", "Generates cat pairs via API.")
    Container(jaeger, "Jaeger", "Distributed tracing platform", "Stores traces, logs, metrics")
}

Container(trace_analyzer, "Your solution", "A tool for finding anomalies in runtime data")

Rel(user, backend_api, "Uses", "HTTPS")

Rel_Neighbor(backend_api, database, "Reads from and writes to", "sync, JDBC")
Rel(backend_api, python_api, "Requests cat pairs", "")

Rel_Neighbor(python_api, jaeger, "Sends traces", "")
Rel(backend_api, jaeger, "Sends traces and metrics", "")
Rel(trace_analyzer, jaeger, "Requests runtime data")

@enduml
